<?php
require_once '../../config/db.php';
require_once '../../config/config.php';
require_once '../../config/session.php';
require_once '../../vendor/GoogleAuthenticator.php';

requireExecutive();

if (!isCoreAdmin()) {
    setFlash('error', 'Access denied.');
    header('Location: index.php'); exit;
}

$db          = getDB();
$currentUser = currentUser();
$staffId     = (int)($_GET['id'] ?? $_POST['staff_id'] ?? 0);
if (!$staffId) { header('Location: index.php'); exit; }

// Fetch staff
$staffStmt = $db->prepare("SELECT * FROM users WHERE id = ? AND is_active = 1");
$staffStmt->execute([$staffId]);
$staffUser = $staffStmt->fetch();
if (!$staffUser) {
    setFlash('error', 'Staff not found.');
    header('Location: index.php'); exit;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verifyCsrf();

    $ga        = new PHPGangsta_GoogleAuthenticator();
    $newSecret = $ga->createSecret();

    // Save new secret, reset ga_enabled to 0 (staff must re-verify)
    $db->prepare("UPDATE users SET ga_secret = ?, ga_enabled = 0, updated_at = NOW() WHERE id = ?")
       ->execute([$newSecret, $staffId]);

    // Send email with new secret
    try {
        require_once '../../config/mailer.php';
        $html = emailWrapper("
            <h2 style='color:#0a0f1e;'>2FA Secret Regenerated</h2>
            <p>Dear <strong>{$staffUser['full_name']}</strong>,</p>
            <p>Your Google Authenticator secret has been regenerated by an administrator.</p>
            <p><strong>Please remove your old MISPro entry from Google Authenticator and add the new one below:</strong></p>
            <div style='background:#f9fafb;border:2px dashed #e5e7eb;border-radius:10px;padding:16px;text-align:center;margin:16px 0;'>
                <div style='font-size:.8rem;color:#9ca3af;margin-bottom:.5rem;text-transform:uppercase;letter-spacing:.05em;'>New 2FA Secret</div>
                <code style='font-size:1.3rem;font-weight:700;letter-spacing:.15em;color:#1f2937;'>{$newSecret}</code>
            </div>
            <p style='font-size:.85rem;color:#6b7280;'>
                Open Google Authenticator → Add Account → Enter setup key → Enter the secret above.
            </p>
            <a href='" . APP_URL . "/auth/login.php'
               style='display:inline-block;background:#c9a84c;color:#0a0f1e;padding:10px 24px;border-radius:8px;text-decoration:none;font-weight:700;margin-top:12px;'>
                Login to MISPro
            </a>
        ");
        sendMail($staffUser['email'], $staffUser['full_name'],
                 '[MISPro] Your 2FA Secret Has Been Regenerated', $html);
    } catch (Exception $e) {}

    logActivity("2FA regenerated for user #{$staffId}", 'users');
    setFlash('success', "2FA secret regenerated for {$staffUser['full_name']}. New secret sent to their email.");
    header("Location: view.php?id={$staffId}"); exit;
}

// GET — show confirmation page
$pageTitle = 'Regenerate 2FA';
include '../../includes/header.php';
?>
<div class="app-wrapper">
<?php include '../../includes/sidebar_executive.php'; ?>
<div class="main-content">
<?php include '../../includes/topbar.php'; ?>
<div style="padding:1.5rem 0;">

<?= flashHtml() ?>

<div class="row g-4 justify-content-center">
    <div class="col-lg-5">

        <div class="card-mis" style="border-left:3px solid #ef4444;">
            <div class="card-mis-header">
                <h5><i class="fas fa-sync" style="color:#ef4444;"></i><span class="ms-2">Regenerate 2FA Secret</span></h5>
            </div>
            <div class="card-mis-body">

                <!-- Staff info -->
                <div class="d-flex align-items-center gap-3 mb-4 p-3"
                     style="background:#f9fafb;border-radius:10px;">
                    <div class="avatar-circle" style="width:44px;height:44px;flex-shrink:0;">
                        <?= strtoupper(substr($staffUser['full_name'], 0, 2)) ?>
                    </div>
                    <div>
                        <div style="font-weight:600;"><?= htmlspecialchars($staffUser['full_name']) ?></div>
                        <div style="font-size:.78rem;color:#9ca3af;"><?= htmlspecialchars($staffUser['email']) ?></div>
                    </div>
                </div>

                <div class="alert alert-warning rounded-3 mb-3" style="font-size:.85rem;">
                    <i class="fas fa-exclamation-triangle me-2"></i>
                    <strong>Warning:</strong> This will invalidate the current 2FA setup.
                    The staff member will need to re-configure Google Authenticator with the new secret.
                </div>

                <form method="POST"
                      onsubmit="return confirm('Regenerate 2FA secret for <?= htmlspecialchars(addslashes($staffUser['full_name'])) ?>? Their current authenticator setup will stop working.');">
                    <input type="hidden" name="csrf_token" value="<?= csrfToken() ?>">
                    <input type="hidden" name="staff_id"   value="<?= $staffId ?>">

                    <div class="d-flex gap-2">
                        <a href="view.php?id=<?= $staffId ?>"
                           class="btn btn-outline-secondary flex-grow-1">
                            Cancel
                        </a>
                        <button type="submit" class="btn flex-grow-1"
                                style="background:#ef4444;color:#fff;border:none;">
                            <i class="fas fa-sync me-1"></i>Regenerate & Email
                        </button>
                    </div>
                </form>

            </div>
        </div>

    </div>
</div>

</div>
<?php include '../../includes/footer.php'; ?>